### ISSUE TITLE
When I turn on http.pool.debug = true, the request is very slow

### ISSUE THREAD

**Issue by zaishui15** [spiral/framework#1035]
- system: window11
- spiral: 3.10.1
- php: 8.2.13

I have over 100 controllers, and I use over 70M of memory for a single work. When I turn on http.pool.debug = true，each request takes 10 seconds. Is there any way to solve this problem.

**Comment by butschster** [comment]
Hi!

Try to set the following env variables:

```
CYCLE_SCHEMA_CACHE=true
TOKENIZER_CACHE_TARGETS=true
```

**Comment by zaishui15** [comment]
Thank you, there's no problem after set TOKENIZER_CACHE_TARGETS=true
