### ISSUE TITLE
newLine() does not exist in console app

### ISSUE THREAD

**Issue by lifewcody** [spiral/framework#1074]
### Description

protected function alert(string $string): void

in HelpersTrait.php calls the following:

$this->newLine();

Which calls $this->output->newLine($count);

Which returns:

[Error]
Call to undefined method Symfony\Component\Console\Output\ConsoleOutput::newLine()
in vendor/spiral/framework/src/Console/src/Traits/HelpersTrait.php:197

### How To Reproduce

In the console application, set to production/prod and call $this->alert(),

### Additional Info

| Q                   | A
| ------------------- | ---
| Framework Version   | 3.11
| PHP version         | 8.3.1
| Operating system    | Linux

**Comment by lifewcody** [comment]
I should have been more specific; It's only when calling `confirmToProceed()`

But then I'm not sure why alert works but not in `confirmToProceed()`

```
if (!$confirmation->confirmToProceed()) {
            return self::FAILURE;
        }
```

**Comment by butschster** [comment]
Hi @lifewcody, thank you for the bug report! Yes, I was able to reproduce the problem. We will fix it soon.
