### ISSUE TITLE
Framework parts and add-ons

### ISSUE THREAD

**Issue by iAvenger01** [spiral/framework#1089]
Hi.
I'm writing a package for a framework and I need some parts of it.
Are the spiral/config and spiral/boot packages up to date? When I try to install them separately I get version 2.14.1, but I am writing for the framework version 3.*.
I don’t want to make the entire spiral/framework dependent on the package.

**Comment by roxblnfk** [comment]
Hi. Try to detect the reason using
`composer why-not spiral/boot 3.11.1`
and
`composer why-not spiral/config 3.11.1`

**Comment by iAvenger01** [comment]
Thank you, I found what the problem was.
The reason was a low PHP version and several package conflicts.
