### ISSUE TITLE
Submit benchmark to https://github.com/kenjis/php-framework-benchmark

### ISSUE THREAD

**Issue by kurtextrem** [spiral/framework#209]
I guess this would attract people and also show the speed of Spiral.

https://github.com/kenjis/php-framework-benchmark

**Comment by wolfy-j** [comment]
Sure, we will deal with it once documentation is updated. The current benchmark is available in this repo: https://github.com/wolfy-j/FrameworkBenchmarks

**Comment by wolfy-j** [comment]
Also, I believe the benchmark you provided is based on Apache mod_php, we are not using it and altering benchmark might be an issue.

**Comment by kurtextrem** [comment]
Thank you!
