### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by myavchik** [spiral/framework#210]
Hello,
I'm following installation instruction at https://github.com/spiral/docs/blob/master/installation.md
And after running
 `spiral configure`
I get an error
`Return value of Spiral\Views\Engines\TwigEngine::makeLoader() must implement interface Twig\Loader\LoaderInterface, instance of Spiral\Views\Engines\Twig\LoaderBridge returned in TwigEngine.php at line 228`

**Comment by alexndr-novikov** [comment]
Hi @myavchik ,

I've checked this case, the problem really exists in the first version of the framework (that is used by spiral/application). We'll check it out and fix asap.
But for now you can try new framework version, that has no problems in configuration. It is the most up to date framework version (and doc is on its way)

You can find installation instructions here: 

https://github.com/spiral/app

**Comment by wolfy-j** [comment]
Hi,

I have been on vacations. Alex is correct, all of the new functionality is currently available in 2.0 version which is installable via spiral/app. We will check what happens with Twig dependency for 1.0, we are not using default bundle by ourselves so this issue left unnoticed.
