### ISSUE TITLE
Automate release process for all components

### ISSUE THREAD

**Issue by wolfy-j** [spiral/framework#213]
- automatic tagging
- automatic release

**Comment by rauanmayemir** [comment]
Any examples to look at for inspiration?

**Comment by wolfy-j** [comment]
I think Symfony has one. I haven't look deep into it yet.

**Comment by SerafimArts** [comment]
It seems I did it purely by accident :D

@wolfy-j for the future `vendor/bin/monorepo-builder release vX.Y.Z` then `composer split`
