### ISSUE TITLE
Migrate command doesn't show failed migration

### ISSUE THREAD

**Issue by Eugentis** [spiral/framework#221]
The migrate command doesn't show which migration was failed when you make many migrations and one of the migrations is failed.

You can detect it with verbose mode but it will be more comfortable to see the name of failed migration.

**Comment by vvval** [comment]
@Eugentis can you please provide an example output with and without verbosity flags?

**Comment by EvgenyBarinov** [comment]
[Moved ](https://github.com/spiral/migrations/issues/15) to spiral/migrations. Please close this issue
