### ISSUE TITLE
JsonPayloadMiddleware should not try to decode body for GET requests

### ISSUE THREAD

**Issue by rauanmayemir** [spiral/framework#222]
Currenly, GET requests with `Content-Type: application/json` will throw exception because `JsonPayloadMiddleware` tries to decode its empty body.

I think, middleware should fall back to empty arrays in such cases.

Correction: it fails for any kinds of requests with empty body.

**Comment by wolfy-j** [comment]
Can you provide me the snapshot (runtime/snaphots) info? Or the details about the specific error.

**Comment by wolfy-j** [comment]
Technically, the 400 client error is expected when the payload is not valid. I need to think if easing validation is good approach.

**Comment by rauanmayemir** [comment]
Yes, I thought of that, too. But from practical standpoint, it would be an odd request to tell API consumers not to include `Content-Type: application/json` if they're not sending any data.

**Comment by wolfy-j** [comment]
OK, I'll check if we can add it to the next release.

**Comment by butschster** [comment]
Fixed https://github.com/spiral/framework/pull/267
