### ISSUE TITLE
Feature request: "--offline" key for "php app.php configure"

### ISSUE THREAD

**Issue by vGhost2000** [spiral/framework#226]
Простите по англ. я не очень писатель.

**Проблема:**
Как правило на сборочных машинах нет доступа к базам, а на машинах где всё вертится файловые системы рид онли. По этому в момент сборки существует необходимость произвести "подогрев" приложения сгенерировав все runtime кеши. Бяда в том, что при выполнении на сборочной машине
`php app.php encrypt:key -m .env && php app.php configure -vv`
Фреймворк пытается установить соединение с бд и команды валятся.
При локальной разработке такая проблема отсутствует и всё отлично работает.

**Решение:**
Реализовать "--offline" (или подобный) ключ для указанных выше команд, который укажет фреймворку сделать всё тоже самое, но при этом не пытаясь устанавливать соединение с внешними сервисами такие как бд, раббиты, редисы и прочие сервисы которые могут использоваться в процессе подогрева. Тогда это не будет ломать сборку приложения в CI.

З.Ы. пасиб за отличный проект!

**Comment by aywan** [comment]
Уточните пожалуйста конфигурацию, версию, базы.
Скелетон приложение на данных командах не ходит в БД. Возможно проблема не актуальна в текущий момент.
