### ISSUE TITLE
Error handler for JSON:API specs

### ISSUE THREAD

**Issue by R3VoLuT1OneR** [spiral/framework#231]
I just started to implement [JSON:API](https://jsonapi.org/format/) server with Spiral framework. JSON:API requires use of `application/vnd.api+json` media type usage for HTTP requests/responses.

For now I found some small problem with error handling for `Accept: application/vnd.api+json` as current implementation of `ErrorHandleMiddleware` checks only for specific `application/json` content type. And I want to receive JSON formated error for such request.
https://github.com/spiral/framework/blob/95deaee7eb403364d0b82acf3fc337fda7c094f0/src/Http/Middleware/ErrorHandlerMiddleware.php#L112

As well for JSON:API the response type must be set to: `application/vnd.api+json`.
https://github.com/spiral/framework/blob/95deaee7eb403364d0b82acf3fc337fda7c094f0/src/Http/Middleware/ErrorHandlerMiddleware.php#L113

As a fix for that I want just extend `ErrorHandleMiddleware` with my own implementation, just override the `ErrorHandleMiddleware::renderError` method.

But `ErrorHandleMiddleware` is a final class so I can't do that. 
https://github.com/spiral/framework/blob/95deaee7eb403364d0b82acf3fc337fda7c094f0/src/Http/Middleware/ErrorHandlerMiddleware.php#L33

As well similar problem exists in `JsonPayloadMiddleware::isJsonPayload` method:
https://github.com/spiral/framework/blob/95deaee7eb403364d0b82acf3fc337fda7c094f0/src/Http/Middleware/JsonPayloadMiddleware.php#L50

Can contribute some code to fix this issues, but first would like to hear your suggestions how you guys want this to be fixed if you want this to be fixed at all on framework level or should I write my own error handling and json payload middleware?

**Comment by wolfy-j** [comment]
Feel free to update both middlewares with the new content type (ideally abstract it a bit). The finals are only to make sure that we have proper damage control (i.e. freedom to change internal API without affecting your projects).

I would avoid extending such classes, but rather inject new functionality via composition or directly (as it seems like a simple content-type header).

Thank you for your help!

**Comment by wolfy-j** [comment]
Hi, sorry for the delay of PR from my end: 
Can you provide an example of indended use (we can add it to docs). Is there a reason for non immutable value? Is it going to be carries inside psr-7 attrs?

**Comment by R3VoLuT1OneR** [comment]
Hi,

I was thinking about using it as helper for parsing the "Accept" header and later use it in `ErrorHandleMiddleware` to check if there is JSON content type. As current implementation `$request->getHeaderLine('Accept') == 'application/json'` will fail for complex "Accept" header.
With an option to use it later for different internal features.

There is no real reason for non immutable value, just was thinking about option generate Accept header to make external HTTP calls. Can change it to immutable implementation.

Wasn't thinking about putting it in psr-7 attributes.
But it is good idea, to create some middleware that will parse Accept header and put the result as psr-7 attribute:
```
$request->withAttribute(
  AcceptHeader::class,
  AcceptHeader::fromString($request->getHeaderLine('Accept')
);
```

But:
1) ErrorHandler will depend on this middleware so we need add it by default to all request and it is going to affect performance of all http requests. Performance can be compensated a bit with lazy parsing of the header.
2) Current implementation can be helpfull for parsing "Accept-Encoding", "Accept-Charset" should we add them somehow to this middleware as well? What will the attribute name?

**Comment by wolfy-j** [comment]
Ok, can you please move it to immutable implementation so it’s consistent across all components? Thank yiu

**Comment by wolfy-j** [comment]
Please use immutable implementation to be consistent across components.

1. Lazy will work, error handler can parse content type by itself when error happen and no attr already exists. 
2. We can create a set of Constants and use them instead of class name for attribute.

**Comment by wolfy-j** [comment]
Please use immutable implementation to be consistent across components.

1. Lazy will work, error handler can parse content type by itself when error happen and no attr already exists. 
2. We can create a set of Constants and use them instead of class name for attribute.

**Comment by R3VoLuT1OneR** [comment]
@wolfy-j After learning more about the framework I think to move the "AcceptHeader" parser to the `InputManager` creating `AcceptHeaderBag` and adding new bag like `accept`, `encoding`, `charset` that will parse the `Accept`, `Accept-Encoding`, `Accept-Charset`.

**Comment by wolfy-j** [comment]
This could work, but we treat InputManaget as "fatter" dependency. Native PSR-7 support will be better in this case as you can use the component in other frameworks with fewer dependencies.

**Comment by wolfy-j** [comment]
Can this one be closed?
