### ISSUE TITLE
Make php app.php update return proper exit code on failed command

### ISSUE THREAD

**Issue by alexndr-novikov** [spiral/framework#234]
We've faced an issue when using Swagger doc on our project.
When file contains documentation in annotation which is not imported we get behavior like this:

![image](https://user-images.githubusercontent.com/7372962/72802683-60b01900-3c5d-11ea-839c-11ff30c175a4.png)

But final return code is 
![image](https://user-images.githubusercontent.com/7372962/72802703-6a398100-3c5d-11ea-9bc9-7934ffa8a625.png)

so we can't guarantee that code will work even using this in CI, cause problem is suspended and build passes.

Can you add some optional flag for update and configure commands to make these pipelines fail when some exception caught?

**Comment by vvval** [comment]
Fixed in https://github.com/spiral/console/pull/1

**Comment by vvval** [comment]
@alexndr-novikov will release it tomorrow after a check on a local machine with real failing sequence

**Comment by alexndr-novikov** [comment]
Still returning 0 as exit code instead of 1 expected on fail

**Comment by vvval** [comment]
@alexndr-novikov see [v2.4.6](https://github.com/spiral/framework/releases/tag/v2.4.5) release
>You need to pass `true` as a 3rd argument to `$app->serve()` call

**Comment by wolfy-j** [comment]
Please verify if this can be closed.
