### ISSUE TITLE
Typo + unused parameter

### ISSUE THREAD

**Issue by ncou** [spiral/framework#251]
Hi,

Nice framework. Looking throw the code I found one typo and an unused parameter. Do you need a PR ?

1) The character "t" is missing in the class name (+file name) "RrDispacher" instead of "RrDispa**t**cher".
https://github.com/spiral/framework/blob/master/src/Http/RrDispacher.php#27

2) The `DirectoriesInterface $dirs` parameter is useless in the constructor for the Publisher class, and should be removed. Or am i missing something ?
https://github.com/spiral/framework/blob/master/src/Module/Publisher.php#L35

Keep up the good work.

**Comment by wolfy-j** [comment]
Thank you for the kind word :)

PR will be appreciated. The ticket will remain open until your comments addressed.

**Comment by wolfy-j** [comment]
Addressed in the next release. Thank you

**Comment by ncou** [comment]
Look like i was to slow for the PR :) I see you commit, should i close the ticket ? or you are keeping it open until the next release ?
