### ISSUE TITLE
Против абстракции над Key Value Storage

### ISSUE THREAD

**Issue by Nex-Otaku** [spiral/framework#256]
По поводу единой абстракции над KV. Есть несколько аргументов против этой идеи:

1. Существование фреймворка без этого модуля, на протяжении долгого времени, показывает, что не очень-то он и нужен. Ведь до сих пор хорошо обходились без него.

2. Проблема быстрого подключения новых приложений на фреймворке "из коробки" ко всяким KV, может быть легко решена отдельными драйверами для каждого KV. 

3. Предлагаю сделать отдельные драйверы для Redis, Memcache и т.п. без "единого на всех KV API".
Плюсы такого решения:
	+ не нужно урезать набор команд
	+ легко поддерживать совместимость с последними версиями самого хранилища
	+ фреймворк не связан жёстко с пакетом драйвера и не зависит от него, легче обновлять сам фреймворк
	+ пакет драйвера не связан жёстко с фреймворком, больше свободы, быстрее эволюционирование
	+ независимость пакета драйвера даёт возможность для передачи его в руки надёжного maintainer'а из коммьюнити, тем самым избавив разработчиков фреймворка от лишней работы.
	+ можно сделать драйверы только 2-3 для самых популярных KV, оставив остальное коммьюнити, и сэкономив кучу времени.
	
4. Минусы единого API, соответственно, противоположные:
	- урезаный набор команд ограничивает автора приложения
	- много работы для авторов фреймворка для поддержки пакета KV в актуальном состоянии, разрешение конфликтов разных KV и API
	- нужно следить за совместимостью KV пакета и самого фреймворка, замедляет развитие фреймворка
	- увеличенная нагрузка на авторов фреймворка отнимает время, замедляет работу над ядром фреймворка
	
5. В общем случае разработчику не требуется никакой абстракции. Большинство приложений пишутся под конкретные технологии и за весь жизненный цикл не требуют переключения на другую технологию или какого-то масштабирования. Такой разработчик возьмёт пакет под конкретную технологию, раз подключит и всё время будет пользоваться.

6. Когда абстрагирование от конкретного KV всё же требуется. Допустим, у нас суровый хайлоад и нужно обкатывать каждое KV без изменения кода. В таком случае, гораздо лучшим решением будет абстракция-прослойка в коде приложения. Например, общий код репозитория и несколько конкретных хранилищ-обёрток под каждый KV. Это позволяет тонко настроить работу с каждым KV в самой "обёртке", что как раз очень хорошо соответствует практике хайлоада.

7. Дополнительный слой абстракции усложняет понимание кода.

**Comment by Kirzilla** [comment]
Ладно memcache или memcachedb - их еще можно назвать KV (хотя кейсов использования кроме как KV хоть отбавляй), но redis назвать KV просто язык не поднимается...

**Comment by zavodilo** [comment]
Может сделать все же абстракцию. А в документации привести пример, как ее выпилить, если она не нужна?

**Comment by wolfy-j** [comment]
Привет, мы вернёмся к моменту абстракции после обновления контейнера сервисов РР. Мы нашли несколько архитектурных моментов которые можно серьезно улучшить. Работа пока ведётся приватно.

**Comment by wolfy-j** [comment]
KV abstraction already complete in 2.0 for the caching purposes.
