### ISSUE TITLE
Corrupted binary

### ISSUE THREAD

**Issue by waghanza** [spiral/framework#266]
Hi @wolfy-j,

`spiral` fails to install when dowloading in https://github.com/the-benchmarker/web-frameworks/blob/master/php/spiral/config.yaml#L6

~~~php
Updating binary file of Spiral Server
Downloading Spiral Server archive for Linux

[============================] 100%  1 sec/1 sec  0KB
Unpacking spiral-2.4.18-linux-amd64.tar.gz

In spiral line 183:
                                                                               
  internal corruption of phar "/opt/web/rr_zip_2530.tar.gz" (truncated entry)  
                                                                               

get-binary [-l|--location LOCATION]
~~~

Regards,

PS : Tested on `php:7.4-fpm-alpine` and `fedora 32`

**Comment by 48d90782** [comment]
@waghanza tag 2.4.18 was removed. It had a dependency from RR 1.8.1 (tag also was removed). I'll update the release in a moment with updated RR dependency.

**Comment by 48d90782** [comment]
I mean, tag 2.4.18 will be available in a moment :)

**Comment by 48d90782** [comment]
@waghanza Should be fine now: https://github.com/spiral/framework/releases/tag/v2.4.18

**Comment by waghanza** [comment]
I confirm
