### ISSUE TITLE
Check method \Spiral\Migrations\Migrator::isRestoreMigrationDataRequired

### ISSUE THREAD

**Issue by elrusso** [spiral/framework#268]
There might be cases when we have two or more databases in project which has tables called `migrations` then that method will return `true` and migration will fail. In my case second db's from laravel app (I'm transfering some app from laravel to spiral).
I solved this problem by renaming  migration table to `spiral_migrations`.
Maybe make sense to add some prefixes for framework tables by default, like `spiral_` or smth else.

**Comment by wolfy-j** [comment]
Discussed in chat.
