### ISSUE TITLE
problem to install on Ubuntu

### ISSUE THREAD

**Issue by netwarp** [spiral/framework#270]
I try to install the framework on my virtual machine but there is an error message:

Deprecation Notice: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /usr/share/php/Composer/Downloader/GitDownloader.php:223
Deprecation Notice: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /usr/share/php/Composer/Downloader/SvnDownloader.php:132
  - Installing spiral/app (v1.1.3)
    Downloading: 100%

Created project in blog
Loading composer repositories with package information
Updating dependencies (including require-dev)

  [ErrorException]
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

Config: Ubuntu: 18, PHP: 7.4.6
Thanks for your help

**Comment by wolfy-j** [comment]
It seems like you have older version of Composer. The error happen even before execution reached spiral.

**Comment by wolfy-j** [comment]
FYI: https://github.com/composer/composer/issues/7783

**Comment by netwarp** [comment]
I have installed the latest version and everything works. Thanks :)
