### ISSUE TITLE
[router] Проблема с сабдоменами

### ISSUE THREAD

**Issue by SerafimArts** [spiral/framework#290]
*This is a moved issue from the https://github.com/spiral/router repository created by @Alexfilus*

нашёл баг в роутере
использую такие паттерны:
```php
'//[<sub>.]' . $domain . '/uslugi-i-tseny[/<first>][/<second>]',
'//[<sub>.]' . $domain . '/reviews/<slug>.html',
'//[<sub>.]' . $domain . '/about[/<action>]',
```
везде добавляется 
```php
->withDefaults([
            'sub' => 'moscow',
        ])
```
так вот, для домена 2 уровня sub приходит не null, и не moscow, а пустая строка
Когда других переменных нет, например
```php
 '//[<sub>.]' . $domain . '/sitemap', 
```
всё ок, sub работает правильно

**Comment by butschster** [comment]
https://github.com/spiral/framework/issues/303
