### ISSUE TITLE
Container isn't compatible with PHP 8

### ISSUE THREAD

**Issue by samdark** [spiral/framework#294]
https://github.com/spiral/framework/blob/master/src/Core/src/Container.php#L197 is not compatible with PHP 8 giving

```
Method ReflectionParameter::getClass() is deprecated
```

It could be replaced with something like:

```php
$name = $param->getType() && !$param->getType()->isBuiltin() ? new ReflectionClass($param->getType()->getName()) : null;
```

**Comment by samdark** [comment]
https://github.com/yiisoft/yii-cycle/runs/1058384659#step:12:83

**Comment by wolfy-j** [comment]
I think @SerafimArts already addresses this in upcoming release.

**Comment by SerafimArts** [comment]
@samdark I already researched this issue a while ago. The example you specified is not entirely correct, since does not work with union types.

**Comment by samdark** [comment]
Yes, that I know. Union types should be handled like https://github.com/yiisoft/injector/blob/master/src/Injector.php#L198

**Comment by roxblnfk** [comment]
@SerafimArts when are you planning to resolve this issue?

**Comment by SerafimArts** [comment]
@roxblnfk At the moment I have slightly different plans, but this issue is a priority one.

As far as I understand, this problem is currently a blocker for you?

**Comment by roxblnfk** [comment]
> As far as I understand, this problem is currently a blocker for you?

No, just the tests are red

**Comment by SerafimArts** [comment]
> No, just the tests are red

Only when running on PHP 8 =) This is the reason why this version is not in CI yet: https://github.com/spiral/framework/blob/master/.github/workflows/main.yml#L63

**Comment by DanRaduDragomir** [comment]
Seems like this reappeared in the latest release:

```log
ERRO[0000] [grpc]: [grpc]: unable to connect to worker:  [ErrorException]                                     
Method ReflectionParameter::getClass() is deprecated 
in /code/vendor/spiral/php-grpc/src/Method.php:68
```

and yes, looking in that file we will find:
```php
public static function match(\ReflectionMethod $method): bool
    {
        if ($method->getNumberOfParameters() != 2) {
            return false;
        }

        $ctx = $method->getParameters()[0]->getClass();
        $in = $method->getParameters()[1]->getClass();
[...]
```
