### ISSUE TITLE
[router] Проблема с сабдоменами

### ISSUE THREAD

**Issue by Alexfilus** [spiral/framework#303]
нашёл баг в роутере
использую такие паттерны:
```
'//[<sub>.]' . $domain . '/uslugi-i-tseny[/<first>][/<second>]',
'//[<sub>.]' . $domain . '/reviews/<slug>.html',
'//[<sub>.]' . $domain . '/about[/<action>]',
```
везде добавляется 
```
->withDefaults([
            'sub' => 'moscow',
        ])
```
так вот, для домена 2 уровня sub приходит не null, и не moscow, а пустая строка
Когда других переменных нет, например
```
 '//[<sub>.]' . $domain . '/sitemap', 
```
всё ок, sub работает правильно

**Comment by vvval** [comment]
@Alexfilus 
> ```
> '//[<sub>.]' . $domain . '/uslugi-i-tseny[/<first>][/<second>]',
> ```

По идее, тут надо было так
```
'//[<sub>.]' . $domain . '/uslugi-i-tseny[/<first>[/<second>]]',
```
-----
Про сам вопрос:
> так вот, для домена 2 уровня sub приходит не null, и не moscow, а пустая строка

В каком случае? без самого значение поддомена или даже с ним?

-----
> Когда других переменных нет, например
>  ```
> //[<sub>.]' . $domain . '/sitemap'
> ```
> всё ок, sub работает правильно

Работает правильно КАК, подставляется дефолт или что?

**Comment by Alexfilus** [comment]
> > так вот, для домена 2 уровня sub приходит не null, и не moscow, а пустая строка
> 
> В каком случае? без самого значение поддомена или даже с ним?
> 
без, дефолт не подставляется

> > Когда других переменных нет, например
> > ```
> > //[<sub>.]' . $domain . '/sitemap'
> > ```
> > 
> > 
> > всё ок, sub работает правильно
> 
> Работает правильно КАК, подставляется дефолт или что?

Да, дефолт подставляется как и ожидалось

**Comment by butschster** [comment]
@Alexfilus thank you for a bug!
