### ISSUE TITLE
[filters] `toArray` and `getFields` should account for composite array of filters

### ISSUE THREAD

**Issue by rauanmayemir** [spiral/framework#313]
Currently, calling both `getFields` and `toArray` returns child fields as is, leaving you with an array of unwrapped filter objects.

I think filters should somehow check the schema and serialize nested objects.

**Comment by vvval** [comment]
@rauanmayemir are you sure? according to `toArray()` functionality, its output is a plain data array, all objects are converted to values

**Comment by rauanmayemir** [comment]
@vvval Not if you have a field that is an array of filter objects.
