### ISSUE TITLE
Stream wrapper doesn't implement stream_cast

### ISSUE THREAD

**Issue by vvval** [spiral/framework#343]
On a custom checker that implements a FileTrait (with its `resolveFilename()` method) and such a construction:
```php
$filename = $this->resolveFilename($file);
(new \finfo())->file($filename, FILEINFO_MIME_TYPE);
```
Got error
```finfo::file(): Spiral\Streams\StreamWrapper::stream_cast is not implemented!```

**Comment by roxblnfk** [comment]
@vval hello. Is the issue still relevant?
