### ISSUE TITLE
[tokenizer] Undefined constant T_PAAMAYIM_NEKUDOTAYIM

### ISSUE THREAD

**Issue by weijer** [spiral/framework#348]
![image](https://user-images.githubusercontent.com/12838756/98506371-48fe5b80-2296-11eb-9b0f-f4b250ad7ff9.png)

PHP version : 7.3.22

**Comment by weijer** [comment]
Yes, I didn't turn on this extension.
thank you!

**Comment by SerafimArts** [comment]
I repoen this issue because improvements are required so that this problem does not arise in the future:

 Need to add `ext-tokeniser` into the Composer's `require` section: https://github.com/spiral/framework/blob/master/src/Tokenizer/composer.json
