### ISSUE TITLE
[data-grid-bridge] Writer ability to detect active driver.

### ISSUE THREAD

**Issue by EvgenyBarinov** [spiral/framework#349]
Is it possible to detect what driver used in case when some custom query filter used?
For example if you are using some custom writer `\Spiral\DataGrid\WriterInterface` you will be able to define some db-dependent filter (ILIKE for postgresql as an example).

If I am correct you can make it if $source for writeFilter method will have some interface and can detects his active driver.

**Comment by vvval** [comment]
selectQuery has 
```php
    public function getDriver(): ?DriverInterface
    {
        return $this->driver;
    }
```
not sure about `Select`

**Comment by vvval** [comment]
@EvgenyBarinov Just create your own writer similar to `QueryWriter`, register it in the compiler and place such function inside:
```php
    protected function targetAcceptable($target): bool
    {
        if (class_exists(SelectQuery::class) && $target instanceof SelectQuery) {
            return $target->getDriver() instanceof PostgresDriver;
        }

        if (class_exists(Select::class) && $target instanceof Select) {
            return $target->buildQuery()->getDriver() instanceof PostgresDriver;
        }

        return false;
    }
```
