### ISSUE TITLE
Remove all "final"-s, and use "protected" instead of "private"

### ISSUE THREAD

**Issue by klkvsk** [spiral/framework#353]
## Description

Spiral is a nice fresh framework, but it's not extendable, which is not a good thing for a framework.

There is a broad usage of "final" keyword in framework's classes. Most of these are not helpful, they are harmful. By taking away the ability to extend, you force developers to create very odd workarounds. Composition instead of inheritance does NOT work everywhere. 

## Example

Some recent examples: 

1. I wanted to add a caching layer in ORM. My custom Mapper would override queueUpdate/queueDelete and create my custom Command that writes to cache after executed. My custom Repository would read from cache before doing select.
<br>Can I extend Mapper or Command? I can not, due to final. Ok, so I'll do a composition around them, proxying most of methods to base Mapper/Command. Now I'd like to tell Spiral to use my Mapper instead of its own. There is a FactoryInterface, that factories Mappers, nice. And there is one and only implementation - Factory class. Would be easy to override `mapper()` in it, right? No, Factory is final. Ok, so I'll just copy-paste 90% of its code to MyFactory. Now I need to wire it somehow into a bootloader. But CycleBootloader already injects default FactoryInterface. Can I extend CycleBootloader to change it? No. Guess we're copy-pasting CycleBootloader too.<br>

2. I wanted to put additional fields within a result set of `$repository->select()`. Let's say, I want to do something like `$postsRepo->select()->withColumn("COUNT(posts.id) as post_count")->getIterator()`. I'll use custom Iterator here too, which fills something like custom-defined "$extra" array in an entity with `[ 'post_count' => 10 ]` so I'm able to call `$post->getExtra('post_count')`. 
<br>Long story short, Select is final, Iterator is final. Even if they would not be, there are private-s in them. Not extendable.<br>

3. I started with adding auth to my app. I did everything by the cookbook, but wanted to add a session validator: after actor is found I'd check if their password has not been changed, and invalidate token otherwise.
<br>I could easily do it with extending AuthBootloader and overriding getActor method in it. But its final, so the only thing I can do is to write a middleware that does what I need. But if some other middleware runs before it, it will suppose the user is correctly authorized, even if their session needs to be invalidated.

---

I understand each framework has its rights to put some opinions into its API design. But I just do not see strong reasons to put final in most of the cases where it is. Would be interesting to see counter-examples if I am mistaken.

**Comment by wolfy-j** [comment]
I'm not against it. We have these abstractions for a while, so I assume it's safe to open some of them. 

@SerafimArts will assist after completing current activities with the new component.
