### ISSUE TITLE
Ability to work with nullable fields in request

### ISSUE THREAD

**Issue by Eugentis** [spiral/framework#354]
Sometimes when you are working with PATCH-requests you need to work with nullable fields.
And if you want to make existing value in db to null you must send it in request with null value.
Current class `Spiral\Filters\Filter` can't detect that field was received with null-value. It is ignored now.

Could add ability to detect if field was received but with null?

**Comment by vvval** [comment]
> Current class Spiral\Filters\Filter can't detect that field was received with null-value. It is ignored now.

@Eugentis what does it mean "It is ignored now."? Does validation fail the check or it treated as an empty string instead

**Comment by Eugentis** [comment]
It can't be detected via hasField
If I am correct filter doesn't received it in private data list

**Comment by vvval** [comment]
@Eugentis If the field didn't come into request the request won't have it. `hasField()` shows exactly false here. But still `getField()` will return null, as the null is a default value if the field is absent. I don't fully understand your case, can you please provide a piece of code that doesn't work as expected?

**Comment by Eugentis** [comment]
Very old issue

I can't provide useful details for described case
