### ISSUE TITLE
Open Spiral\Validation\Validator for extension

### ISSUE THREAD

**Issue by vladgorenkin** [spiral/framework#358]
Hi,

I'm writing package that allows to validate objects with annotated properties. Here is a gist of what validated object looks like so you could get the idea:

```
final class TestData implements \ArrayAccess
{
    use ArrayAccessTrait;

    /**
     * @Assert\Type\NotEmpty(
     *   asString=true,
     *   message="Should not be empty",
     *   conditions={"withAll": {"typeNotNull"}}
     * )
     */
    public $typeNotEmpty;

    /**
     * @Assert\Type\NotNull(message="Should not be null")
     */
    public $typeNotNull;
    ...
```

Validation is built upon Spiral's default validator which only works with arrays or \ArrayAccess objects. So either validated object needs to implement \ArrayAccess (which is a not very clean solution, but works), or validated object needs to be properly casted to array every time Validator is constructed/Validator::withData is used (which is worse, especially if it gets any more complex than calling get_object_vars).

I'd like to avoid either option and just extend existing validator to fit my purpose. The problem is validator is closed for extension via inheritance, so I'd need to copy existing implementation which I'd like to avoid.

Do you think it is safe to open Spiral\Validation\Validator for extension (and tweak ValidatorInterface a bit to allow broader type of arguments to be used as data)?

Thanks in advance

**Comment by vvval** [comment]
@vladgorenkin 
Hi, first of all, `ValidatorInterface` doesn't' stick to arrays, at least all it has is `iterable` phpdoc.
What changes do you want to perform in the custom validator? I assume that the main difference would be "converting" entities to an array. As for me, having it final is ok if there's a suitable interface, you can use composition inside of your validator:
```php
class MyValidator implements ValidatorInterface
{
    private $validator;

    private function convert($data): array
    {
        //do something
    }

    public function __construct(object $data, array $rules, $context, RulesInterface $ruleProvider)
    {
        $this->validator = new Validator($this->convert($data), $rules, $context, $ruleProvider);
    }

    public function withData($data): ValidatorInterface
    {
        $validator = clone $this;
        $validator->validator = $validator->validator->withData($this->convert($data));
        return $validator;
    }
    //...
}

**Comment by vladgorenkin** [comment]
> What changes do you want to perform in the custom validator?

I want to replace hasValue/getValue methods to make them work with not ArrayAccess'able objects so I don't have to implement it in validated classes. Your solution works I guess, though I'd like to avoid unneccessary conversion to array: it may become complicated and costy to convert to array if additional logic is applied (getting validated value through getter method and etc). And ValidationInterface needs to be changed even with your solution

Thanks

**Comment by vvval** [comment]
@vladgorenkin I see now. I can remove final declaration from class and add it to `validate` method. Will this work for you?

**Comment by vladgorenkin** [comment]
Absolutely

**Comment by vladgorenkin** [comment]
Another possible solution could be to use some kind of property accessor in hasValue/getValue methods, which would work with arrays and objects. Is something like this already implemented in Spiral? Could it be used elsewhere in the framework?

**Comment by vvval** [comment]
@vladgorenkin do you mean extract the array data to a separate "dataProvider"? I thought about it a little. We have several options here:
- extract data to a provider with the ability to switch arrays to objects or whatever it can be
- extract `validate()` to a standalone trait or class (then you'll have to copypaste just a little boilerplate)
- introduce abstract validator with the `validate()` in it. Will look like the prev option

I assume we need advice from you, @SerafimArts. As for me, I'd introduce `DataProviderInterface` and extract `validate()` into a `DateValidatorInterface` (the name is weird, I know). So the initial `ValidatorInterface` will extend them both.

**Comment by vladgorenkin** [comment]
> do you mean extract the array data to a separate "dataProvider"?

Not exactly. Something like this:

```php
final class Validator implements ValidatorInterface
{
    ...
    public function __construct($data, array $rules, $context, RulesInterface $ruleProvider, DataExtractor $dataExtractor = null)
    {
        $this->data = $data;
        $this->errors = [];
        $this->rules = $rules;
        $this->context = $context;
        $this->provider = $ruleProvider;
        $this->dataExtractor = $dataExtractor ?? new PropertyAccessor();
    }
    ...
    /**
     * @inheritdoc
     */
    public function getValue(string $field, $default = null)
    {
        return $this->dataExtractor->getValue($this->data, $field, $default);
    }

    /**
     * @inheritdoc
     */
    public function hasValue(string $field): bool
    {
        return $this->dataExtractor->hasValue($this->data, $field);
    }
    ...
}
```

See https://symfony.com/doc/current/components/property_access.html to get an idea of what PropertyAccessor is

**Comment by vvval** [comment]
@vladgorenkin I see, so in that case, moving `final` to the `validate()` might be enough. But still, there's room for refactoring, because you'll still have to redeclare all properties (they are private) and `parent::__construct()` will be totally omitted.

**Comment by vvval** [comment]
@vladgorenkin please check the PR if it fits your demands

**Comment by vladgorenkin** [comment]
Looks perfect, thanks!
