### ISSUE TITLE
Command to receive RBAC permissions

### ISSUE THREAD

**Issue by Eugentis** [spiral/framework#369]
## Description

It will be useful if you will add command to display roles with assigned rules.

## Example
Simplified example:
```php
foreach ($rbac->getRoles() as $role) {
    echo \sprintf("%s:\n", $role);

    foreach ($rbac->getPermissions($role) as $permissionName => $permissionRule) {
        echo \sprintf(
            "-- %s: %s\n", $permissionName, $permissionRule
        );
    }
}
```

**Comment by Eugentis** [comment]
Please take a look at this [PR](https://github.com/spiral/security/pull/17)

**Comment by wolfy-j** [comment]
This PR should be pointing to this monerope. spiral/security is read-only split.

**Comment by Eugentis** [comment]
https://github.com/spiral/framework/pull/455
