### ISSUE TITLE
Mailer implementation without queueing

### ISSUE THREAD

**Issue by Anlamas** [spiral/framework#398]
## Description

There is only spiral/mailer implementation and it works with queue.
Would be better have a spiral/Mailer implementation without queueing, so you can work with object in view files.

## Example

1. Push a job into queue
2. In the job pass object(s) into Spiral\Mailer\Message
3. Send a mail.

```
public function invoke($payload): void
{
    $order = $this->orders->findByPK($payload['orderId']);

    $message = new Message(
        'mail/order/new',
        $payload['email'],
        [
            'order' => $order,
        ],
    );
    
    $this->mailer->send($message);
}
```

**Comment by butschster** [comment]
Hi @Anlamas! Could you check this PR https://github.com/spiral/framework/pull/514 ?
