### ISSUE TITLE
Mail Message options are not serialized for queue

### ISSUE THREAD

**Issue by vladgorenkin** [spiral/framework#402]
## Description

Not sure if it is intended behavior but currently MessageInterface::$options are not serialized, so you can't use them when sending mails asynchronously

```
$message = (new Message(...))->setOptions(['foo' => 'bar']);
MailQueue->send($message);

// SomeRenderer.php
$message->getOptions(); // []
```

**Comment by SerafimArts** [comment]
Merged (available since v2.8.3 release https://github.com/spiral/framework/releases/tag/v2.8.3)
