### ISSUE TITLE
[DataGrid] cell.text processing for subarrays

### ISSUE THREAD

**Issue by Eugentis** [spiral/framework#404]
## Description

Sometimes it is required to display simple text from some child entity like createdBy.fullName

But in current implementation cell.text can't display such values:
```
<grid:cell.text name="createdBy.fullName" label="Created By">
    {createdBy.fullName}
</grid:cell.text>
```

Cell text will be more functional in case it can work with child arrays

**Comment by wolfy-j** [comment]
I assume we can simply make text alias to template.

**Comment by AndrewKirkovski** [comment]
https://github.com/spiral/toolkit/releases/tag/v1.1.65
