### ISSUE TITLE
spiral/http ResponseWrapper problem

### ISSUE THREAD

**Issue by alexndr-novikov** [spiral/framework#412]
### Description

When you return data from controller method - you can suddenly get an exception 

```
[InvalidArgumentException]
Status code has to be an integer between 100 and 599. A status code of 0 was given
```

### How To Reproduce
Case 1: 

```php
/**
     * @Route(
     *     route="api/v2/test,
     *     group="api",
     *     name="api.test",
     *     methods="GET"
     * )
     */
    public function airportRawList(ResponseWrapper $responseWrapper): \Psr\Http\Message\ResponseInterface
    {
        return $responseWrapper->json(
            [
                'status' => 'text',
                'data' => 'data',
            ]
        )->withStatus(200);
    }
```

In this case 200 is ignored, and 'text' is set as http code ((int)'text' === 0) and we get the exception again.
Expected behavior is when you set `->withStatus(200)` - you just get `{"status": "text", "data": "data"}` as a response with HTTP code 200

Case 2:

Same happens with array returned:

```php
/**
     * @Route(
     *     route="api/v2/test,
     *     group="api",
     *     name="api.test",
     *     methods="GET"
     * )
     */
    public function airportRawList(ResponseWrapper $responseWrapper): array
    {
        return [
            'status' => 'text',
            'data' => 'text'
        ];
    }
```

If this is expected (which makes sense) this aspect should be added to documentation.

### Additional Info

| Q                   | A
| ------------------- | ---
| Framework Version   | v2.7.8
| PHP version         | PHP 7.4.19 (cli)
| Operating system    | Linux alpine:3.13

**Comment by SerafimArts** [comment]
Has been fixed in 2.7.9 https://github.com/spiral/framework/releases/tag/v2.7.9
