### ISSUE TITLE
Add support for psr/container:^2

### ISSUE THREAD

**Issue by elazar** [spiral/framework#431]
`spiral/core` is [currently pinned](https://github.com/spiral/core/blob/v2.8.9/composer.json#L19) to using `psr/container:^1`.

`psr/container:^2` is [now available](https://github.com/php-fig/container/releases/tag/2.0.1). The [changes between the two](https://github.com/php-fig/container/compare/1.1.1...2.0.1) look minor enough that upgrading may not require much effort.

I'm happy to submit a PR if there's agreement on either supporting both versions or replacing support for v1 with support for v2.

**Comment by wolfy-j** [comment]
If they are compatible it should not be a problem.

**Comment by elazar** [comment]
Unfortunately, upon closer inspection, it looks like there is a breaking change, so support would have to be shifted to v2 alone.

Related: symfony/symfony#42058

**Comment by wolfy-j** [comment]
We will aim at 3rd version then.
