### ISSUE TITLE
[Storage] Error with s3-server prefix usage

### ISSUE THREAD

**Issue by Eugentis** [spiral/framework#434]
### Description

I have S3 configuration for storage with prefix dev
```
servers' => [
        'awsServer' => [
            'adapter' => 's3',
            'version' => 'latest',
            'region' => env('AWS_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'key' => env('AWS_KEY'),
            'secret' => env('AWS_SECRET'),
            'endpoint' => env('AWS_PUBLIC_URL'),
            'prefix' => env('AWS_PREFIX', null), // dev
            'options' => [
                'use_path_style_endpoint' => true,
            ],
        ],
    ],
```

File was uploaded to AWS with saving in DB path like `aws://img/box/box_img_1`

While I want to build presigned uri I've received
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>my-data/img/box/box_img_1</Key>
<RequestId>NVJNHDS82WEBVHP7</RequestId>
<HostId>U+BBbDwikoyFlZ9t0/aIuVGsyUUWM4EcO8/MulzySQZOuTpcLsLyk13jXRPY6D0KgLEbW98i7Zc=</HostId>
</Error>
```
I think the problem in missing prefix for file path on requesting url in Resolver
Possible reasons can be here:
1. \Spiral\Distribution\Resolver\S3SignedResolver::resolve
2. Spiral\Storage\File::getPathname

As I can see here `\Spiral\Distribution\Resolver\S3SignedResolver::createCommand` there are raw filepath used without prefix

**Comment by SerafimArts** [comment]
Done: https://github.com/spiral/framework/pull/445
