### ISSUE TITLE
The benchmark link doesn't work.

### ISSUE THREAD

**Issue by roquie** [spiral/framework#437]
### Description

The Benchmark link doesn't work.
 
### How To Reproduce

https://www.techempower.com/benchmarks/#section=test&runid=ba6c12a4-d54d-4a9e-825b-abde0ef6d6a2&hw=ph&test=fortune&l=zg24n3-f&c=6&a=2&o=e

<img width="1680" alt="Screenshot 2021-08-06 at 12 04 52" src="https://user-images.githubusercontent.com/3214290/128486162-50dbc4a2-af5c-4aa1-ba3f-036f83b5521e.png">

**Comment by wolfy-j** [comment]
Fixed.
