### ISSUE TITLE
[Logs]: Null lines at logs after manual clearing logs

### ISSUE THREAD

**Issue by Eugentis** [spiral/framework#440]
### Description

A lot of times it was detected that in case when logs manually cleared spiral writes logs with a lot of NULL records.
It seems spiral stores last line where it should be added next line and tries to fill all previous lines with null values....

### How To Reproduce

Make some actions with sql queries on project with db
Clear sql-.....log manually in any application
Make some changes in entities and run `app migrate`
Check sql-...log file
File contains a lot of null lines `NULL\nNull\n`

### Additional Info

| Q                   | A
| ------------------- | ---
| Framework Version   | v2.8.
| PHP version         | 7.4
| Operating system    | MacOS

**Comment by wolfy-j** [comment]
Hmmm, we are using Monolog for log solution... I wonder if they have a similar bug.
