### ISSUE TITLE
Custom Dispatcher

### ISSUE THREAD

**Issue by zaishui15** [spiral/framework#443]
When I use custom dispatcher,  it works normally ，but no output will be printed to the screen！

`rsp, err = s.rr.Exec(&roadrunner.Payload{
    Context: Context,
    Body:    Body,
})`

public function serve()

    {
        $worker = $this->container->get(Worker::class);
        \error_log("no output to the screen!");
        while (($body = $worker->receive($ctx)) !== null) {
            try {
                $worker->send($body );
            } catch (Throwable $e) {
                $worker->error((string)$e->getMessage());
            }
            $this->finalizer->finalize(false);
        }
    }

**Comment by SerafimArts** [comment]
Please make sure `error_log` redirects output to `php://stderr`

**Comment by zaishui15** [comment]
Thank you. must join log listener

```
package test
import (
	gp ".../service/test"
	"github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
	rr "github.com/spiral/roadrunner/cmd/rr/cmd"
	"github.com/spiral/roadrunner/cmd/util"
)
func init() {
	cobra.OnInitialize(func() {
		if rr.Debug {
			svc, _ := rr.Container.Get(gp.ID)
			if svc, ok := svc.(*gp.Service); ok {
				svc.AddListener((&debugger{logger: rr.Logger}).listener)
			}
		}
	})
}
type debugger struct{ logger *logrus.Logger }
func (s *debugger) listener(event int, ctx interface{}) {
	if util.LogEvent(s.logger, event, ctx) {
		return
	}
}
```
