### ISSUE TITLE
Possible bug during Container resolving arguments

### ISSUE THREAD

**Issue by ncou** [spiral/framework#448]
Hi,

Looking at the source code i think i found a bug. 
In the container during the argument resolving, there is an "assertType()" function used on the scalar (https://github.com/spiral/framework/blob/master/src/Core/src/Container.php#L451) when the value is null there is a check on the reflection parameter isOptional and getDefaultvalue === null, but this will not work if the typehint is "?string" the exception will be thrown to indicate null is not a correct value for this parameter.
I think you should use $parameter->allowsNull() to simplify the code and avoid this bug.

Hope this is clear and could help the projet.

**Comment by roxblnfk** [comment]
Hi. Thank you for the issue. Bug was verified and will be fixed in the next release.

**Comment by ncou** [comment]
good news, keep up the good work !
