### ISSUE TITLE
Attributes edge case: argument indices in wrong order

### ISSUE THREAD

**Issue by donquixote** [spiral/framework#456]
### Description

Numeric argument indices in wrong order behave differently in NamedArgumentsInstantiator vs native attributes. 

### How To Reproduce

Insert in `NamedArgumentsInstantiatorTestCase::testNamedConstructorInstantiatable()`.

```php
        $object = $this->new(NamedArgumentConstructorFixture::class, [
            1 => 'one',
            0 => 'zero',
        ]);

        if (PHP_VERSION_ID < 80000) {
            $this->assertSame('zero', $object->a);
            $this->assertSame('one', $object->b);
        }
        else {
            $this->assertSame('one', $object->a);
            $this->assertSame('zero', $object->b);
        }
        
        $this->assertSame(null, $object->c);
```
The test will pass.
It shows that `NamedArgumentsInstantiator::resolveParameters()` does not fully replicate PHP 8 named parameters behavior.

This is an edge case, but PHP 8 does not produce an error if the indices are inversed.

**Comment by donquixote** [comment]
I have a pull request ready for `spiral/attributes`. It also adds new tests.
But now I wonder if instead I should make a pull request here in `spiral/framework`?
How can I bring my branch from the subtree split back into the common repo?

**Comment by SerafimArts** [comment]
Yep. All PRs should be directed to this repository (in this case, branch `2.8`).

I think the easiest way is to just copy the files from your repository into the `src/Attributes/*` directory and commit the changes.

**Comment by donquixote** [comment]
> I think the easiest way is to just copy the files from your repository into the src/Attributes/* directory and commit the changes.

Is there no way to do it on git level?
I have multiple commits that I would like to keep in sequence.
But ok, will do it the hard way this time :)

**Comment by SerafimArts** [comment]
> Is there no way to do it on git level?

IDK. I have never encountered such a thing ¯\\\_(ツ)_/¯

**Comment by donquixote** [comment]
I did the following:
- Add my local attributes repo as a remote. Fetch.
- Cherry-pick the 3 commits from the feature branch in the attributes repo. Git uses heuristics to determine the file and directory where changes should be applied, but these heuristics are limited.
- Use `git rebase -ir HEAD^^^´, move files that were created in the wrong place, and amend the respective commits.
