### ISSUE TITLE
Attributes: Named args to variadic params in PHP < 8

### ISSUE THREAD

**Issue by donquixote** [spiral/framework#458]
I was going to post this as a comment in #457, but I think it is better as a separate issue.

I don't expect this to be solved any time soon or perhaps ever. But I think it can be good to have it discussed and findable somewhere.

## Description
In PHP 8+, variadic parameters can accept named arguments, like so:

```php
function f(...$args) {}
f(x: 5);  // Won't work in PHP < 8: "Parse error: syntax error, unexpected ':', expecting ')'"
f(...['x' => 5]);  // Won't work in PHP < 8: "Cannot unpack array with string keys"

#[Attribute]
class A {
  public function __construct(...$args) {}
}

// Won't work in PHP < 8 with NamedArgumentsInstantiator.
#[A(x: 5)]
class C {}
```

I am wondering, when using this for attributes, could there be a hacky workaround?

We'd have to create an artificial alternative constructor. that copies the function body from the existing constructor, and somehow give it access to the private members of the class. Seems wild.

The feature would be useful to replace annotations that currently allow arbitrary options in addition to the known parameters.

**Comment by SerafimArts** [comment]
`NamedArgumentsInstantiator` repeats (well, or tries hard) the behavior of the original PHP in case of calling `newInstance()`. Therefore, in this implementation, nothing beyond what the PHP itself does will not be implemented.

Obviously, to pass variadic arguments, it is enough not to pass a name:
```php
#[A(5)] // Instead of #[A(x: 5)]
class C {}
```

And for repeating the behavior of `doctrine/annotations`, there is another `DoctrineInstantiator` that repeat the behavior of original doctrine annotations. If there are any specific problems, it makes sense to create an issue where the problem with an example of the difference in behavior between the original doctrine and the spiral emulator will be described.

Frankly, I don’t remember a single case when the variadic syntax in the constructor would be used in annotations (inside constructor). Can you please have such an example?

**Comment by donquixote** [comment]
> Can you please have such an example?

I was considering to build an attribute class like this, supporting custom / 3rd party options.

```php
class A {
  private string $id;
  private string $label;
  private array $options;
  public function __construct(string $id, string $label, ...$options) {
    $this->id = $id;
    $this->label = $label;
    $this->options = $options;
  }
  public function getCustomOption(string $k) {
    return $this->options[$k];
  }
}

#[A("example", "Example", translate: true, encrypt: true)]
class Example {}

// or using fully named args:
#[A(id: "example", label: "Example", translate: true, encrypt: true)]
class Example {}
```

An alternative would be to make $options a proper array argument, so the attribute would look like this instead.

```php
#[A("example", "Example", options: ['translate' => true, 'encrypt' => true])]
class Example {}

// Or with purely sequential args:
#[A("example", "Example", ['translate' => true, 'encrypt' => true])]
class Example {}
```

I have not fully

**Comment by donquixote** [comment]
> And for repeating the behavior of doctrine/annotations, there is another DoctrineInstantiator that repeat the behavior of original doctrine annotations.

For a new package I would like to fully move towards attributes, but ideally have as much expressiveness as was possible with doctrine annotations.
I don't think it is a good idea to combine the doctrine instantiator with attributes. Doing that would make the parsed attributes behave differently than native attributes.

**Comment by SerafimArts** [comment]
I think I get it. Is there a problem with the `...['key' => 'val']` syntax? It was added in 8.1 and accordingly causes syntax errors in the native reader.

```php
class ExampleAttribute
{
    public function __construct($a, $b, ...$c) { ... }
}

///

#[ExampleAttribute(a: 42, b: 23, c: ...['x' => 42])]
class Example {}
```

In this case, the "try/catch" solution at https://github.com/spiral/framework/issues/457#issuecomment-929474978 will solve this problem too.

**Comment by donquixote** [comment]
`c: ...['x' => 42]`

I tried this and it doesn't work: https://3v4l.org/mefjY

Also I don't see how any change in the attribute syntax would help us to send the named variadic args into the constructor.

**Comment by SerafimArts** [comment]
> I tried this and it doesn't work

Hmmmm.... Yep. You're right =( 
Even in PHP 8.1: "Cannot use unpacking in attribute argument list".

> Also I don't see how any change in the attribute syntax would help us to send the named variadic args into the constructor.

In any case, you have to write your own `CustomInstantiator` to implement this behavior, like: `new AttributeReader(new CustomInstantiator())`. Although the "instantiator" is an internal class, however, we will not change the package structure at least until version 3.0.

**Comment by donquixote** [comment]
The PR in https://github.com/spiral/framework/pull/459 now contains test cases for variadic parameters.

Here is a commit that introduces tests without changing functionality.
It shows that currently the behavior is different in PHP 7.x vs PHP 8.x.
https://github.com/spiral/framework/pull/459/commits/87636ed8b26c6012de6a2df62cecdc53d316871e#diff-29c63f9ad0124a1b557cff231474ce33caf0a7d54a98bb008ce1054bd3e50405R234

And with the fixes from that PR, we get a dedicated error message:
https://github.com/spiral/framework/pull/459/commits/34842c770ec34b57a62b6942798790efa5d4fa56#diff-29c63f9ad0124a1b557cff231474ce33caf0a7d54a98bb008ce1054bd3e50405R238
