### ISSUE TITLE
Attributes: NativeAttributeReader does not respect inheritance for $name parameter.

### ISSUE THREAD

**Issue by donquixote** [spiral/framework#461]
https://3v4l.org/Xn2sb
With native `$rc->getAttributes($name)`, the `$name` parameter filters by the class name, without taking into account inheritance.
The NativeAttributeReader uses this native filtering.

The FallbackAttributeReader, on the other hand, does respect inheritance.
In `FallbackAttributeReader::format()`:

```php
            if ($prototype->name !== $name && $name !== null && !\is_subclass_of($prototype->name, $name)) {
```

So, what should be the "canonical" behavior? Should we always respect inheritance, or never, or make it optional?

**Comment by SerafimArts** [comment]
> So, what should be the "canonical" behavior? 

This seems to be unnecessary logic. The behavior should be similar to the native reader. 

Thanks for finding problems!

**Comment by donquixote** [comment]
I think for users it could be useful to take inheritance into account.

**Comment by SerafimArts** [comment]
Yes and no. This is a fairly popular "problem", but there is no definitive solution for it how to deal with attribute conflicts. Moreover, there is no unambiguous hierarchy in the case of a chain of traits and interfaces.

```
class A implements B, C
{
    use D, E;
}
```
1) A, B, C, D, E ?
2) or A, D, E, B, C ?

What if some trait contains a contains another trait? What if an interface implements an another interface?

I think this functionality will be useful as a separate package, which allows not only to specify the required inheritance chain, but also to correctly merge attributes (In the case of duplicate attributes at "different levels" of inheritance - sometimes they need to be combined into one, instead of getting two different attributes at once: one from the child, the other from the parent).

**Comment by donquixote** [comment]
Actually all that anyone could expect from this is the behavior equivalent to `instanceof` and `is_a()`, that is also used for covariance and contravariance.

> Moreover, there is no unambiguous hierarchy in the case of a chain of traits and interfaces.

I don't think traits should have anything to do with it.

> What if some trait contains a contains another trait? What if an interface implements an another interface?

I don't see the problem. What am I missing here?

> but also to correctly merge attributes (In the case of duplicate attributes at "different levels" of inheritance - sometimes they need to be combined into one, instead of getting two different attributes at once: one from the child, the other from the parent).

This seems like a separate problem.
For attributes I would expect to only get the attributes that are defined directly on the class or method itself, not on some parent class.
Duplicate attributes should simply be treated as two distinct objects.
Any kind of "merging" should be done by the user / consuming code.

A useful pattern can be "active" attribute objects.
E.g. for annotated routes in controller classes, we could have this:

```php
interface RouteModifierInterface {
  function modifyRoute(Route $route);
}
#[Attribute]
class RouteAccess implements RouteModifierInterface {
  public function __construct(
    private string $permissionName
  ) {}
  public function modifyRoute(Route $route) {
    $route->setPermission($this->permissionName);
  }
}
```
So the route discovery would look for attributes that implement RouteModifierInterface, and call ->modifyRoute() on each of them.

**Comment by SerafimArts** [comment]
I apologize, I misunderstood the case the first time.

The native reader also takes inheritance into account: https://github.com/spiral/attributes/blob/master/src/Internal/NativeAttributeReader.php#L47

The second argument of the `getAttributes` method: https://3v4l.org/pnf53

**Comment by donquixote** [comment]
Ah, I was not aware. Thanks!

**Comment by donquixote** [comment]
I think we can close this. It was my mistake.
