### ISSUE TITLE
[Logger] Allow to add processors to monolog

### ISSUE THREAD

**Issue by wodor** [spiral/framework#474]
## Description

Currently LogFactory just  returns one processor (https://github.com/spiral/framework/blob/cc6cb37254e8185561f12c9e6d1c0ade824ff9a3/src/Bridge/Monolog/src/LogFactory.php#L132) 
I guess the way is to replace it in my application, but it looks like it is not easy to do because it is embedded in MonologBootloader  https://github.com/spiral/framework/blob/2.8/src/Bridge/Monolog/src/Bootloader/MonologBootloader.php
So I need to "duplicate" that code too.

## Example
It would be great to be able to define processors to add in a  bootloader and have the constructor of implementation of `LogsInterface` that accepts a collection of processors.

**Comment by butschster** [comment]
Sounds good! Thank you!

**Comment by wodor** [comment]
I am willing to work on a solution for this, it would be best if I get some direction from the authors.

**Comment by butschster** [comment]
I think processors could be migrated to [MonologConfig](https://github.com/spiral/framework/blob/cc6cb37254e8185561f12c9e6d1c0ade824ff9a3/src/Bridge/Monolog/src/Config/MonologConfig.php#L43) like handlers.

**Comment by butschster** [comment]
Hi @wodor! Could you check PR https://github.com/spiral/framework/pull/506?
