### ISSUE TITLE
[views] view breaks on concurrent view rendering.

### ISSUE THREAD

**Issue by azjezz** [spiral/framework#477]
### Description

Attempting to render 2 or more view concurrently where the view contains a non-blocking I/O operation, results in completely wrong, and partial output.

### How To Reproduce

profile.php:

```
<Articles>
<?php foreach($user->getArticles() as $article): ?>
  <Article />
<?php endforeach; ?>
<Articles>
```

main.php

```
use Psl\Async;

final class User {
  public function getArticles(): array
  {
    Async\sleep(0.1); // simulate a database query, e.g: articles is a lazy collection
    return [1, 2];
  }
}

[$one, $two, $three] = Async\parallel([
  static fn() => $views->render('user.php', ['user' => new User()]),
  static fn() => $views->render('user.php', ['user' => new User()]),
  static fn() => $views->render('user.php', ['user' => new User()]),
]);
```

### Additional Info

| Q                   | A
| ------------------- | ---
| Framework Version   | all
| PHP version         | PHP 8.1, using Fibers
| Operating system    | any

This happens due to this code here: https://github.com/spiral/framework/blob/2.8/src/Views/src/Engine/Native/NativeView.php#L49-L71

To explain further, the first `render` will call `ob_start()`, `<Articles>` will be written to the buffer, and then a non-blocking I/O operation takes place.

since we are running multiple render operations concurrently, the second, and third calls will be invoked, resulting in `ob_start()` getting called 2 more times, and 2 more `<Articles>` being written to the buffer.

Once the first I/O operation completes, the rest of the template gets rendered, and `ob_get_clean` gets called, resulting in the `<Articles>` being written 3 times in the first template buffer, and missing from the 2 other.

This is the simplest test, if we are rendering 100 different templates at the same time, where each template is different, the output will make no sense at all.

---

See twigphp/Twig#3599 for more information.

---

Solutions:

Sadly, since spiral doesn't compile the templates the same way as twig, there's no way to actually do https://github.com/twigphp/Twig/pull/3600 ( which fixes the issue in Twig ).

The only solution to fix this in Spiral is: queued operations ( see: https://github.com/twigphp/Twig/issues/3599#issuecomment-993007764 )

The only way to do queue operations is by having an event loop, and if Spiral is going to integrate an event loop at any point, https://github.com/revoltphp/event-loop should be the number 1 choice, as it's used by Amphp, Psl, and could easily be hooked with ReactPHP.

The reason an event loop is need ( over trying to call `sleep()` on a loop ), is to ensure that it doesn't block other things when it's used in a long running process server, these things could be database queries, http requests, ... etc.

**Comment by azjezz** [comment]
Note: if https://github.com/spiral/roadrunner-worker/issues/19 would be implemented, this needs to be fixed, as handling concurrent connections in the same worker, could result in concurrent templates being rendered at the same time.

**Comment by azjezz** [comment]
Here's a fix using revolt event loop suspensions:

```php
<?php

/**
 * Spiral Framework.
 *
 * @license   MIT
 * @author    Anton Titov (Wolfy-J)
 */

declare(strict_types=1);

namespace Spiral\Views\Engine\Native;

use Psr\Container\ContainerInterface;
use Spiral\Core\ContainerScope;
use Spiral\Views\ContextInterface;
use Spiral\Views\Exception\RenderException;
use Spiral\Views\ViewInterface;
use Spiral\Views\ViewSource;
use Revolt\EventLoop;

final class NativeView implements ViewInterface
{
    /*** @var ViewSource */
    protected $view;

    /** @var ContainerInterface */
    protected $container = null;

    /** @var ContextInterface */
    protected $context;

    private ?EventLoop\Suspension $suspension = null;

    /**
     * @param ViewSource         $view
     * @param ContainerInterface $container
     * @param ContextInterface   $context
     */
    public function __construct(ViewSource $view, ContainerInterface $container, ContextInterface $context)
    {
        $this->view = $view;
        $this->context = $context;
        $this->container = $container;
    }

    /**
     * {@inheritdoc}
     */
    public function render(array $data = []): string
    {
        $this->suspension?->suspend();

        $this->suspension = EventLoop::createSuspension();

        ob_start();
        $__outputLevel__ = ob_get_level();

        try {
            ContainerScope::runScope($this->container, function () use ($data): void {
                extract($data, EXTR_OVERWRITE);
                // render view in context and output buffer scope, context can be accessed using $this->context
                require $this->view->getFilename();
            });
        } catch (\Throwable $e) {
            while (ob_get_level() >= $__outputLevel__) {
                ob_end_clean();
            }

            $suspension->resume();
            $this->suspension = null;

            throw new RenderException($e);
        } finally {
            //Closing all nested buffers
            while (ob_get_level() > $__outputLevel__) {
                ob_end_clean();
            }
        }

        $content = ob_get_clean();
        $suspension->resume();
        $this->suspension = null;
        return $content;
    }
}
```

**Comment by wolfy-j** [comment]
Interesting. Thank you for the report, indeed rendering of the native view won't work at the moment. So you saying that Twig already has a fix?

**Comment by azjezz** [comment]
> So you saying that Twig already has a fix?

Yes, and no. The issue for Twig is BC breaking, so unlikely to be merged any time soon, however, it can be fixed in Spiral views by using suspension as mentioned above.

This will also work for native view.

**Comment by azjezz** [comment]
actually, the suspension method won't work in spiral... since you can multiple instances of view, so it needs to be done in the engine.

**Comment by azjezz** [comment]
another solution, which would be a bit harder to implement, but would work pretty well, is compiling PHP templates, the can be done by parsing the source file of the template, and rewriting it.

1. every `echo ${expr}`,`print ${expr}`, `echo(${expr})` and `print(${expr})` could be replaced by `$content .= ${expr}`.
2. every `printf(${expr}, ${args})` could be replaced by `$content .= sprintf(${expr}, ${args})`
3. every content outside of PHP tags can be quote-escaped and surrounded with double quotes.

from `user.php`:
```php
<div>
  <p><?= $user->getUsername() ?></p>
  <small><?= $user->getBio() ?></small>
</div>
```

to:
```php
<?php
$__template_content__ = '';
$__template_content__ .= "<div>\n";
$__template_content__ .= "  <p>";
$__template_content__ .= $user->getUsername();
$__template_content__ .= "</p>\n";
$__template_content__ .= "  <small>";
$__template_content__ .= escape($user->getUsername());
$__template_content__ .= "</small>\n";
$__template_content__ .= "</div>\n";

return $__template_content__ ;
```

This will also add the ability for spiral to have helper functions within templates that don't actually exist at runtime, via extensions.


```php
<div>
  <p><?= $user->getUsername() ?></p>
  <small><?= escape($user->getBio()) ?></small>
</div>
```

```php
<?php
$__template_content__ = '';
$__template_content__ .= "<div>\n";
$__template_content__ .= "  <p>";
$__template_content__ .= $user->getUsername();
$__template_content__ .= "</p>\n";
$__template_content__ .= "  <small>";
$__template_content__ .= $this->callFunction('escape', $user->getUsername());
$__template_content__ .= "</small>\n";
$__template_content__ .= "</div>\n";

return $__template_content__ ;
```

where `$this->callFunction` looks something along these lines:

```php
public function callFunction(string $function, ...$args): mixed {
  if (function_exists($function)) {
    return $function(...$args);
  }

  foreach($this->extensions as $extension) {
    $helpers = $extension->getHelpers();
    foreach($helpers as $helper) {
      if($helper->getName() === $function) {
        return $helper->invoke(...$args);
      }
    }
  }

  throw new RuntimeError('call to undefined helper function %s');
}
```

**Comment by azjezz** [comment]
I'm closing this issue as i personally have no effort to put into working on it.

I think it would a good idea to document that the behavior in a concurrent application is unpredictable, and spiral should be avoided in such an environment.

more information: https://twitter.com/azjezz/status/1476295773616848896?s=20
