### ISSUE TITLE
Allow custom loader in ViewManager

### ISSUE THREAD

**Issue by vladgorenkin** [spiral/framework#488]
## Description

It is impossible to replace default view loader for ViewManager because ViewLoader is hardcoded. I'd suggest replacing ViewLoader with LoaderInterface. My use case is loading templates from database.

```php
...
final class ViewManager implements ViewsInterface
{
    ...
    public function __construct(ViewsConfig $config, FactoryInterface $factory)
    {
        ...
        $this->loader = $factory->make(ViewLoader::class, [
            'namespaces' => $config->getNamespaces(),
        ]);
       ...
    }
```

**Comment by butschster** [comment]
As I understrand you have an ability to bin ViewLoader with alternative realization
```php
$conatiner->bind(ViewLoader::class, function() {
    return new DatabaseViewLoader(...);
});
```

**Comment by vladgorenkin** [comment]
This is ok as a temporary solution, but this behavior is confusing at least. Any type check (for example if container did one at the end of get() call) is going to fail because technically DatabaseViewLoader is neither ViewLoader, nor it's child (because ViewLoader is final)
