### ISSUE TITLE
Improve ExceptionsHandler

### ISSUE THREAD

**Issue by butschster** [spiral/framework#508]
Add ability to handle exceptions with creating custom handlers for different exception classes for HTTP and console environment.

**Comment by gam6itko** [comment]
@butschster How do you look at copying the approach from symfony? 
If an error occurs ExceptionHandler will dispatch ExceptionEvent, and will use event response if it exists.
https://symfony.com/doc/current/reference/events.html#kernel-exception

I very need this feature. I can even write the PR
