### ISSUE TITLE
Move `JsonPayloadConfig` in the right place

### ISSUE THREAD

**Issue by butschster** [spiral/framework#534]
It should be there `src/Framework/Bootloader/Http`, but I'm not sure

**Comment by msmakouz** [comment]
@butschster Perhaps, a better place in `src/Http/src/Config`?
In this folder already stored config `src/Http/src/Config/HttpConfig.php`, which is used in bootloader `src/Framework/Bootloader/Http/HttpBootloader.php` and related to HTTP too.
