### ISSUE TITLE
Вывод ошибок локатора в логи

### ISSUE THREAD

**Issue by roquie** [spiral/framework#759]
## Description

> roquie: Рефачил сервис сейчас написанный на SF 3.0 и ошибся в нэймспейсах. Роутинг у меня сделан через аннотации (контроллеры как раз переносились).
Все перенес, сделал красиво, но вот только часть эндпоинтов отвалилось. А информации об этом в консоли/логах/где-либо еще нет. Оставалось только пройтись по всей цепочке работы двух пакетов: роутера и токенайзера.
У последнего есть ClassLocator для поиска контроллеров с роут-атрибутом. Он парсит найденные классы игнорируя ошибки локатора (что в некоторых случаях наверно оправдано): https://github.com/spiral/framework/blob/3.0/src/Tokenizer/src/ClassLocator.php#L24
Именно из-за этого я не мог догнать, в чем причина отвалившихся эндпоинтов. Увидел бы ошибку сразу – поправил и пошел бы дальше.
Так ли необходимо прятать ошибки локатора по умолчанию?
Вижу, что вывод в логи сделан (https://github.com/spiral/framework/blob/3.0/src/Tokenizer/src/AbstractLocator.php#L86), но так как там ничего нет, логгер просто не подключен к фрейму. Может подключить? 

> Wolfy-J: да, стоит подключить, будет признательны если кинешь МР или тикет. Вырублен потому что в вендоре раньше было очень много мусора (хз откуда) и было много ошибок, сейчас в теории уже не будет проблемой т.к. мы индексим меньше папок

**Comment by butschster** [comment]
#763
