### ISSUE TITLE
PHP 8.1: Spiral\RoadRunner\Jobs\Exception\JobsException: Opis\Closure\SerializableClosure implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead

### ISSUE THREAD

**Issue by ostrolucky** [spiral/framework#778]
### Description

I've decided to give this framework a spin (heh heh). So I've installed https://github.com/spiral/app. http://127.0.0.1:8080/ worked fine. However, clicking on [Create Queue Task](http://127.0.0.1:8080/ping.html) leads to this

![image](https://user-images.githubusercontent.com/496233/189500955-bf4a83e8-a5b8-4bd7-a944-b950be9b2ff9.png)

### Additional Info

| Q                   | A
| ------------------- | ---
| Framework Version   | 2.14.0
| PHP version         | 8.1.9
| Operating system    | MacOS

**Comment by butschster** [comment]
Hi @ostrolucky! We are going to release Spiral Framework in a few days. You may start to use it. The problem was solved there.

**Comment by ostrolucky** [comment]
Indeed, this seems changed
