### ISSUE TITLE
DotenvBootloader::loadEnvVariables is not called anymore after Update 2.9 -> 3.1

### ISSUE THREAD

**Issue by daniellienert** [spiral/framework#810]
### Description

After upgrading to spiral/framework 3.1, the `DotenvBootloader::loadEnvVariable` is not called anymore. 
The bootloader is registered, `DotenvBootloader::init()` is called. It seems that `$runningCallbacks` is missing the closure when `$this->fireCallbacks` is called. 

### How To Reproduce

```
class App extends Kernel
{
    protected const LOAD = [
...
        DotEnv\DotenvBootloader::class,
...
]
}
```

### Additional Info

Changing `DotenvBootloader::init` to
```
    public function init(
        AbstractKernel $kernel,
        DirectoriesInterface $dirs
    ): void {
        $kernel->booting(fn (EnvironmentInterface $env) => $this->loadEnvVariables($dirs, $env));
    }
```
everything works as expected again. 

| Q                   | A
| ------------------- | ---
| Framework Version   | 3.1.0 
| PHP version         | 8.1.2 
| Operating system    | Linux

**Comment by butschster** [comment]
Is the problem solved?

**Comment by daniellienert** [comment]
Hey @butschster, 
thanks for your reply! 

I am still investigating right now. Oddly enough it seems to work during the CI pipeline but not local. 
A dump $callbacks in `AbstractKernel::fireCallbacks()` list all closures but not the dotenv clousure.

**Comment by butschster** [comment]
Move the bootloader like in the last version of `spiral/app` https://github.com/spiral/app/blob/master/app/src/App.php#L29

**Comment by daniellienert** [comment]
That apparently fixes the issue! I changed the documentation accordingly in https://github.com/spiral/docs/pull/355
