### ISSUE TITLE
CLI commands throw the Symfony\Component\Console\Exception\InvalidArgumentException

### ISSUE THREAD

**Issue by intro87** [spiral/framework#882]
### Description
Having this in my terminal
```
[Symfony\Component\Console\Exception\InvalidArgumentException]
The "namespace" option does not exist.
in vendor/symfony/console/Input/Input.php:128
```

### How To Reproduce

Try to run `php app.php  create:seeder or create:entity` commands.
```
$ php app.php  create:seeder

 Please provide a value for the 'name' argument:
 > Seeder

[Symfony\Component\Console\Exception\InvalidArgumentException]
The "namespace" option does not exist.
in vendor/symfony/console/Input/Input.php:128

```

### Additional Info

| Q                   | A
| ------------------- | ---
| Framework Version   | ^3.2
| PHP version         | >=8.1
| Operating system    | macOs Ventura 13.0

I followed the [Quick Start](https://spiral.dev/docs/cookbook-quick-start/3.5/en) and got this problem in the middle.
I can create classes manually and so, but it would be nice to have scaffolders. 
Btw `php app.php  create:config same php app.php create:controller and etc` works just fine. 
It might be related to the `database-seeder` package. I tried to dig dipper into the source code but get lost pretty quickly. I would appreciate any help on my issue. Thanks!

**Comment by butschster** [comment]
Hello @intro87 !

Thank you for the issue! Tomorrow we will make a new release with bugfixes!

**Comment by intro87** [comment]
@butschster thank you!
