### ISSUE TITLE
[spiral/pagination] Paginator doesn't calculate `countPages` correctly in constructor

### ISSUE THREAD

**Issue by gam6itko** [spiral/framework#900]
### Description

The current implementation of the Paginator class has an issue in the constructor when we pass the `$count` argument. The problem is with the `$countPages` property which should be calculated based on the `$count` property, but it doesn't. This can cause incorrect pagination calculations.

### Steps to Reproduce:

Create an instance of the `Paginator` class with a non-zero count argument

```php
$paginator = new Paginator(limit: 25, count: 100);
```

### Expected Result:
The `countPages` property should be calculated based on the count property and return the correct value.

```php
$this->assertSame(100, $paginator->count());
$this->assertSame(4, $paginator->countPages());
```

**Comment by butschster** [comment]
Fixed
