### ISSUE TITLE
[spiral/filters] Сonstructor dependency resolution error for Filter

### ISSUE THREAD

**Issue by iAvenger01** [spiral/framework#950]
### Description
While upgrading the Spiral Framework from version 2.8 to 3.7.1, I encountered a problem in the Spiral/filters-bridge package. I have old validation examples, but when I try to access a route with such a filter (there is a bridge package, the bootloader is connected), I encounter an error

### How To Reproduce

**App.php:**
```
use Spiral\RoadRunnerBridge\Bootloader as RoadRunnerBridge;

class App extends Kernel
{
    protected const SYSTEM = [
        CoreBootloader::class,
        TokenizerBootloader::class,
        DotEnv\DotenvBootloader::class,
    ];

    protected const LOAD = [
        // RoadRunner
        RoadRunnerBridge\RoadRunnerBootloader::class,
        RoadRunnerBridge\HttpBootloader::class,
        RoadRunnerBridge\LoggerBootloader::class,
        RoadRunnerBridge\MetricsBootloader::class,

        // Filters bridge
        Framework\Security\FiltersBootloader::class,
    ];
}
```

**My filter:**
```
namespace App\Request;

use Spiral\Filters\Filter;

class LoginRequest extends Filter
{
    /**
     * @var array
     */
    public const SCHEMA = [
        'login' => 'data:login',
        'password' => 'data:password'
    ];

    /**
     * @var array
     */
    public const VALIDATES = [
        'login' => ['notEmpty'],
        'password' => ['notEmpty']
    ];
}
```

**Controller:**
```
class AuthController {
    public function login(
        LoginRequest $loginRequest,
    ): array {
        if (!$loginRequest->isValid()) {
            return [
                'status' => 400,
                'errors' => $loginRequest->getErrors()
            ];
        }
        ...
    }
}
```

### Additional Info

| Q                   | A
| ------------------- | ---
| Framework Version   | 3.7.1
| Filters-bridge Version | 1.0.1
| PHP version         | 8.1.20
| Operating system    | Linux

I get an error related to the fact that the Filter from which I inherit cannot be passed the $data argument in the constructor

**Comment by butschster** [comment]
Hi @iAvenger01 

As I can see, you have to use `Spiral\Filters\Bootloader\FiltersBootloader` instead of `Framework\Security\FiltersBootloader`. Try to replace it and let me know if there will be a problem.

**Comment by iAvenger01** [comment]
Hi @butschster 
Sorry for delay!
I'm getting an error "Undefined class FiltersBootloader". This class should be supplied with spiral/filters-bridge package?
